Pitu/Magane

src/App.svelte
This PR swaps the `<a>`s that were missing `href`s for `<button>`s in order to remove the a11y warnings when building. I also used CSS shorthand to combine the button padding styles and reduced specificity on the danger button selector
=> Remove svelte a11y warnings during build step

src/App.svelte, src/styles/main.scss
Closes #18
~~this PR moves the DOM polling function to maintain the menu position from the `App.svelte` to `main.js`. instead of attaching the Magane container to the Discord base container, we search for the Discord button container and prepend Magane to that in order to avoid having to calculate positioning and possible overlap with textarea content~~
this PR adds a ResizeObserver on the message textarea to determine where to position the Magane menu button. This removes the need for a recurring 500ms `keepMaganeInPlace` function call, which also greatly reduces the number of updates Svelte needs to schedule. Now we only poll for the textarea element when it's missing from the DOM
=> position Magane button with ResizeObserver

src/App.svelte
to match the behavior of the GIF and emoji menus, this PR closes the sticker menu when clicking outside of the Magane UI
=> close sticker menu on click outside of Magane

src/App.svelte, src/styles/main.scss
- fixed vertical scrollbar appearing in packs bottom bar
- properly check if stickers actually get sent (previously it'd say it get sent even in channels where users dont have embed file permission)
- fixed adding line/custom packs not working. previously caused by a faulty logic. the code expected `magane.available` storage item to have already existed, and in the form of an empty array at the very least, which obviously wouldn't be the case with new installations.
- fixed `favoriteStickersData` (used for tooltips of favorited stickers) always skipping the 2nd custom pack. i typoed `-1` with `1` (it was meant to check for not-found return of `Array.findIndex()`, which is `-1`).
---
QoL:
- https://github.com/Pitu/Magane/pull/30/commits/691c0ae3089a185c516a123345825b7ccb3d1b26
- …
=> fixes, QoL changes

src/App.svelte, src/styles/main.scss
- images.weserv.nl for downsizing line stickers to 180p and 100p on the fly (consistency with magane packs)
- line emojis support with `magane.appendEmojisPack(title, packId, count)` - *btw they end up being as big as stickers, lmao*
- fixed 100p variants of magane packs not being used for UI
- and some other smaller tweaks (pls check commit messages)
😘
*ids for line emojis are like hella long - dont mind the aesthetic differences, im using a theme*
*userscript pog*
for line emojis, their internals are slightly different to stickers, so i couldnt really re-use `magane.appendPack()` (e.g. adding a true/false toggle for emojis or smth)
for starters, individual emojis are simply stored as 001, 002, ... N
basically unlike stickers, they're on their individual paths/directories mapped by their …
=> use images.weserv.nl for consistency, line emojis support, and more

src/App.svelte
some early stickers dont have iphone variants
=> switch back to sourcing line android stickers

.github/workflows/deploy.yml, src/App.svelte, src/styles/main.scss
In addition, the Misc tab can probably be used for some basic settings in the future ~~(assuming we don't have Magane integrated into Discord's emojis menu yet)~~
Not using BetterDiscord's built-in plugin settings due to complexity with current implementation
The first 4 micro commits are unrelated to the new feature, but I think they're good to be merged, and seemed small enough not to warrant their own PRs
=> Implement replace and export database

.github/workflows/deploy.yml, package.json, src/App.svelte, src/styles/main.scss, yarn.lock
**Comes with THREE new settings for free!**
---
refactor: replace/export database @ https://github.com/Pitu/Magane/commit/4325450989794a5ca4fabcc7fe50b47d803a5258
still the same functionality, just changed UI text formatting to appear clearer to end-users (since it actually supports Discord's Markdown), and a bit more checks against edge cases
---
ci: update github actions @ https://github.com/Pitu/Magane/commit/dc5cc530e1deed7ed94b163f99c49e7efd0a4d44 + https://github.com/Pitu/Magane/pull/57/commits/2678276c3c186a1819303a30e8084d533d38f5e1
essentially still the same final behavior
instead of using `actions/cache` directly, we instead simply use an option under `actions/setup-node` that does the exact same thing, as it actually uses `actions/cache` under the hood …
=> feat: settings for you, settings for me, settings for everybody AND performance!

src/App.svelte, src/styles/main.scss
As always, I try to do micro commits, so despite the high commit counts, each commit _tries_ to do the bare minimum
---
**3** new settings
---
My custom packs for sample valid JSONs of non-chibisafe album packs https://magane.fiery.me/configs/
=> better custom packs support + import chibisafe albums as custom packs

.github/workflows/deploy.yml
https://github.com/actions/setup-node/issues/416
=> ci: fix node_modules caching

package.json, src/App.svelte
When set to single key (e.g. M), it used to listen to combos too (e.g. Ctrl+M, Ctrl+Alt+M, etc.)
Also added support for listening to only certain side's keys (left ctrl, right alt, etc.), and made the input box for hotkey not to trigger existing hotkey as you're editing it
=> Pr 3.2.2 hotkey fix

package.json, src/App.svelte
sending custom packs and everything else will work just fine, just that magane's built-in packs will temporarily be unavailable, and they'll be presented with relevant error messages on first load, and when trying to send any magane's built-in packs' stickers (if they had any subscribed)
red crosses as placeholder thumbs for magane's built-in packs when the API is down
=> 3.2.3 logic to handle offline magane API

package.json, src/App.svelte
Fix for https://discord.com/channels/361432183010754562/363877247100387329/1021111469959565492 in Discord
---
Added viewport height check to avoid confusion such as in https://discord.com/channels/361432183010754562/363877247100387329/1020321585627926538
Warning toast about it will only appear **once** when opening Magane
Also added a preference setting to disable the check altogether for those that want to use Custom CSS to override the window size anyway
I'm too lazy to make the window more dynamic instead, haha
=> 3.2.4 fix with voice channel's text chat wrapper

package.json, src/App.svelte, src/styles/main.scss
Frequently Used section:
Hidden by default (including the clock shortcut for it on the left/bottom toolbars), until user sends a sticker successfully, unless Frequently Used is explicitly disabled (via the new setting below)
Added 1 new setting:
Defaults to **10**
---
Also improved database hot-reload logic
Previously, when replacing databases, depending on how "complete" the last or the new databases are, some settings may not completely reset to defaults
Some local arrays/objects that Svelte builds the DOM upon used to not reset properly sometimes either
=> 3.2.6 frequently used section + improved database hot-reload logic

package.json, src/App.svelte
Related bug report: https://discord.com/channels/361432183010754562/363877247100387329/1061526826490544198
An alternative method to upload the stickers
Unfortunately, due to it seemingly intended for batch uploads, it has no option to attach text messages into the uploads, so that particular part of the feature is currently disabled
A stop-gap fix as I await investigation results from other similar projects
=> 3.2.9 temporary alternative to mitigate uploads breaking

package.json, src/App.svelte, src/Button.svelte, yarn.lock
- Better fetching of Discord modules
i.e. fetching of chat input, etc., are now done via calling the appropriate Discord/Webpack modules instead of through React/DOM hacks
- Sending stickers now properly include chat input again
- 2 new options (the ones in the middle):
- Restored Discord Permissions check, with always-true fallback if the necessary modules cannot be found (i.e. if Discord changes anything related to permission in the future, at the very least Magane will still always try to send the stickers as-is)
- If user has SEND_MESSAGES permission, but not ATTACH_FILES permission, Magane will automatically fallback into sending the stickers as links
- If the user also has no EMBED_LINKS permission, Magane will cancel sending (since the links will have no previews anyways), but this …
=> 3.2.10 better fetching of discord modules, discord permissions check, send stickers as links, split-view support

package.json, src/App.svelte, src/styles/main.scss, yarn.lock
In the spirit of Genshin getting a bunch of QoLs in the near future, I was slightly motivated to finally get these added too
Input boxes for LINE Store Proxy and Remote Packs now support importing multiple URLs at once, with proper failures handling and whatnot
Importing local JSON files also support adding multiple files at once
Added a new setting that allows toggling sending behavior (as links or as uploads) if holding Ctrl when sending stickers
=> Pr 3.2.12 a couple quality of life changes

.editorconfig, .github/workflows/deploy.yml, README.md, package.json, rollup-bd.config.js, rollup-vencord.config.js, src/App.svelte, src/styles/main.scss, src/vencord-main.js, yarn.lock
I think Discord is programmatically doing styling to scrollbars globally, and the fact that we were using outdated CSS value for `overflow` ([ref](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#values)) might've caused it to fail under certain conditions
Seems to work fine after updating these
**EDIT:** Not ready, turns out using `overlay` was a conscious choice on my end due to styling quirks..
**EDIT 2:** Seems ok with commit https://github.com/Pitu/Magane/pull/87/commits/978e2399d423900e2c62ec553e667c8627a89ce0, but PR pending indefinitely until one day if there are other things to add/fix in the future, since this issue in particular is non-critical
---
**EDIT 3**: I think this should be ready 🤔 
This will now also cause GitHub Actions to build Vencord plugin into `dist` …
=> feat: 3.2.13 bug fixes + more hacks for vencord plugin edition

package.json, src/App.svelte
Had to rethink my initial design of determining then saving the API url during the first time a custom remote pack gets added.
Now it'll always determine the API url even when attempting to update, to allow changing it in the future, if ever required, without breaking existing packs.
This will also cleanly "upgrade" any existing old lolisafe/chibisafe album packs when clicking the Update button on any of them.
=> Pr 3.2.15 fix updating chibisafe albums packs

package.json, rollup-bd.config.js, rollup-vencord.config.js, src/App.svelte, yarn.lock
Fix custom JSON packs.
Yet another oopsie from the recent PRs. All good this time, promise.
---
New option: Mask sticker links with markdown.
In practice, the message will only show "sticker" in blue (clickable link), instead of the whole long urls, for a brief moment. When Discord has the image ready, the text itself will disappear and instead only show the image embed, like the following:
Well, Discord was already doing that even if you send lone image url as-is, but there will be less whiplash from long urls with this I guess.
=> Pr 3.2.16 fix custom json packs + feat mask sticker links with markdown

package.json, rollup-bd.config.js, rollup-vencord.config.js, src/App.svelte, src/meta.txt, src/styles/main.scss
- Sending stickers as uploads now work the same way they used to.
- Improve logic of determining selected textarea, channel, and all that jazz.
- Magane button no longer appearing in textareas of Create Thread and Create Forum Post forms.  
They'd never work there to begin with, since such textareas would've had no active "channel" until they had been created.
- Also add metadata comments for Vencord plugin file. Wanted to expand the update checker for Vencord as well, but it seems like it'll require a bit more experimenting but I'm out of time. I'll probably get back to it at another day so I'm finalizing this PR already.
=> Pr 3.2.18 restore sending as uploads, and a few other things

README.md
vencord moved their docs to a seemingly more permanent solution, so the old link in the vencord guide is 404 now
i have nothing else to add, so ready to merge whenever
=> chore: README.md

README.md, package.json, rollup-bd.config.js, rollup-vencord.config.js, src/App.svelte, src/meta.txt, src/vencord-main.js, src/vencord-native.ts
Vencord changed the constants 10h ago, lmao
https://github.com/Vendicated/Vencord/commit/ed5ed4b80a7b3a50858eefef083b385449147486#diff-556ddcad7cc2db948ab2668ee9611f8d876722173c711e810c5a28e9abb7fc4e
While I was at it, I looked into how the update checker was implemented once again, and figured I could streamline it further to support other platforms, in this case Vencord/Vesktop.
Also fixed an ancient silly bug where Magane won't auto-close its window when switching channel. I kept on forgetting if it was intended or not, and just earlier realized it was not intended (it'd always alert you about having to re-open the window anyway).
=> Pr 3.2.22 fix CSP policies for vencord again, and implement update checker for vencord
